import = ["/Users/h/.config/alacritty/themes/tokyonight_storm.toml"]

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "Buttonless"

[window.padding]
x = 7
y = 0

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

