import = ["/Users/h/.config/alacritty/themes/tokyonight_storm.toml"]

[font]
size = 20

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "none"

[window.padding]
x = 0
y = 0

[keyboard]
bindings = [
  # { key = "H", mods = "Alt", chars = "\u001B[D" },  # Alt + H -> Left Arrow
  # { key = "J", mods = "Alt", chars = "\u001B[B" },  # Alt + J -> Down Arrow
  # { key = "K", mods = "Alt", chars = "\u001B[A" },  # Alt + K -> Up Arrow
  # { key = "L", mods = "Alt", chars = "\u001B[C" },  # Alt + L -> Right Arrow
  { key = "J", mods = "Command", chars = "\u00AA" },
  { key = "K", mods = "Command", chars = "\u00AB" },
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
  { key = "B", mods = "Alt", chars = "\u001BB" },  # Alt + B (Move backward one word)
  { key = "F", mods = "Alt", chars = "\u001BF" },  # Alt + F (Move forward one word)
  { key = "D", mods = "Alt", chars = "\u001BD" },  # Alt + D (Delete the word after the cursor)
  { key = "Backspace", mods = "Alt", chars = "\u001B\u007F" },  # Alt + Backspace (Delete word before cursor)
  { key = "U", mods = "Alt", chars = "\u001BU" },  # Alt + U (Uppercase from cursor to end of word)
  { key = "C", mods = "Alt", chars = "\u001BC" },  # Alt + C (Capitalize the current word)
  { key = ".", mods = "Alt", chars = "\u001B." },  # Alt + . (Insert the last argument of previous command)
  { key = "Y", mods = "Alt", chars = "\u001BY" },  # Alt + Y (Yank the top of the kill-ring)
  { key = "/", mods = "Alt", chars = "\u001B/" },  # Alt + / (Attempt completion)
  { key = "T", mods = "Alt", chars = "\u001BT" },  # Alt + T (Transpose the words around cursor)
  { key = "R", mods = "Alt", chars = "\u001BR" },  # Alt + R (Recall the last command that matches input)
  { key = "N", mods = "Alt", chars = "\u001BN" },  # Alt + N (Search forward through history)
  { key = "P", mods = "Alt", chars = "\u001BP" },  # Alt + P (Search backward through history)
  { key = "Q", mods = "Alt", chars = "\u001Bq" },  # Alt + Q (Not a standard bash shortcut, customizable)
  { key = "Tab", mods = "Control", chars = "\u001b[27;5;9~" },
]
