cask_args appdir: "/Applications", require_sha: true

tap "1password/tap"
tap "cockroachdb/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"

brew "giflib"
brew "little-cms2"
brew "jpeg-xl"
brew "cairo"
brew "docker"
brew "docker-compose"
brew "ghostscript"
brew "jpeg"
brew "pango"
brew "librsvg"
brew "neovim"
brew "node"
brew "python@3.11"
brew "pgcli"
brew "pkg-config"
brew "ripgrep"
brew "tree"
brew "cockroachdb/tap/cockroach"
brew "cockroachdb/tap/cockroach-sql"

cask "1password-cli"
cask "chromium"
cask "font-hack-nerd-font"

vscode "alexandernanberg.horizon-theme-vscode"
vscode "astro-build.astro-vscode"
vscode "be5invis.vscode-custom-css"
vscode "bierner.markdown-mermaid"
vscode "ChakrounAnas.turbo-console-log"
vscode "dbaeumer.vscode-eslint"
vscode "esbenp.prettier-vscode"
vscode "figma.figma-vscode-extension"
vscode "GitHub.codespaces"
vscode "GitHub.copilot"
vscode "ms-azuretools.vscode-docker"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vsliveshare.vsliveshare"
vscode "Prisma.prisma"

mas "things 3", id: 904237743
